services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${US_DB_USER}
      - POSTGRES_PASSWORD=${US_DB_PASS}
      - POSTGRES_DB=${US_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${US_DB_USER} -d ${US_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7
    container_name: redis_container
    command: >
      redis-server
      --requirepass ${US_REDIS_PASS}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${US_REDIS_PASS}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: migrate/migrate
    container_name: migrator_container
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./userservice/migrations:/migrations
    command: >
      -path /migrations
      -database postgres://${US_DB_USER}:${US_DB_PASS}@${US_DB_HOST}:${US_DB_PORT}/${US_DB_NAME}?sslmode=${US_DB_MODE}
      up

  userservice:
    build: ./userservice/
    container_name: userservice_container
    environment:
      - CONFIG=/app/config/docker.yaml
      - REDIS_HOST=${US_REDIS_HOST}
      - REDIS_PORT=${US_REDIS_PORT}
      - REDIS_PASS=${US_REDIS_PASS}
      - REDIS_DB=${US_REDIS_DB}
      - REDIS_TTL_SEC=${US_REDIS_TTL_SEC}
      - DB_HOST=${US_DB_HOST}
      - DB_PORT=${US_DB_PORT}
      - DB_USER=${US_DB_USER}
      - DB_NAME=${US_DB_NAME}
      - DB_PASS=${US_DB_PASS}
      - DB_MODE=${US_DB_MODE}
    depends_on:
      migrator:
        condition: service_completed_successfully 
      redis:
        condition: service_healthy
    ports:
      - 44044:44044
      - 44045:44045
    volumes:
      - ./userservice/config:/app/config
    