services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./userservice/migrations:/migrations
    command: >
      -path /migrations
      -database postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_MODE}
      up

  userservice:
    build: ./userservice/
    container_name: userservice_container
    environment:
      - CONFIG=/app/config/docker.yaml
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_MODE=${DB_MODE}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 44044:44044
    volumes:
      - ./userservice/config:/app/config
    